# ANIMAL TABLE 에서 고양이와 개가 각각 몇 마리인지 조회 하라 
# CULNM 정보 : ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME,SEX_UPON_INTAKE
SELECT ANIMAL_TYPE, 
COUNT (*) AS 'COUNT'
FROM animal 
WHERE ANIMAL_TYPE IN('Cat','Dog')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;