# ANIMAL TABLE 두명 이상 쓰인 이름과 해당 이름의  횟수를 조회 하라 단 이름이 없는 동물은 집계에서 
# 제외하며, 결과는 이름 순으로 정렬 
# CULNM 정보 : ANIMAL_ID, ANIMAL_TYPE, DATETIME, INTAKE_CONDITION, NAME,SEX_UPON_INTAKE
SELECT `NAME`, 
COUNT(`NAME`) AS 'COUNT' 
FROM `ANIMAL` 
WHERE `ANIMAL`IS NOT NULL
GROUP BY `NAME` HAVING `NAME`>=2 ORDER BY `NAME`;